image: node:20

stages:
  - lint
  - build
  - test

vc_lint:
  stage: lint
  script:
    - npm ci
    - npm run lint
  artifacts:
    paths: 
        - chaincodeVC/node_modules/

vc_build:
  stage: build
  script:
    - npm run build
  needs: ["vc_lint"]
  dependencies:
    - vc_lint
  artifacts:
    paths: 
        - chaincodeVC/build/

vc_test:
  stage: test
  script:
    - npm run test
  needs: ["vc_lint", "vc_build"]
  dependencies:
    - vc_lint
    - vc_build
