name:
  Gryphon-app
services:
  keycloak:
    ports:
      - 9090:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME
      - KC_BOOTSTRAP_ADMIN_PASSWORD
    image: quay.io/keycloak/keycloak:26.2.5
    command: start-dev

  gryphon-backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - LOG_PATH=/var/log/myapp/backend
      - KC_BOOTSTRAP_ADMIN_USERNAME
      - KC_BOOTSTRAP_ADMIN_PASSWORD
    volumes:
      - ./logging/logs/backend:/var/log/myapp/backend:rw
      - ./backend/config:/app/backend/config:rw
    networks:
      - monitoring
      - fabric_test

  gryphon-frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    networks:
      - monitoring

networks:
  monitoring: {}
  fabric_test: {}
