image: node:20

# Change to see if the pipeline runs when needed
default:
  rules:
    - changes:
        - backend/**
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

backend-lint:
  stage: lint
  script:
    - cd backend
    - npm ci
    - npm run lint
  artifacts:
    paths:
      - backend/node_modules/
    expire_in: 30 minutes

backend-test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - cd backend
    - npm test
  needs: ["backend-lint"]
  dependencies:
    - backend-lint