services:
  gryphon-backend:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - LOG_PATH=/var/log/myapp/backend
    volumes:
      - ./logs/backend:/var/log/myapp/backend:rw
    networks:
      - monitoring
      - fabric_test

  agent:
    image: grafana/alloy:latest
    container_name: grafana-alloy
    ports:
      - 12345:12345
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
      - ./logs/backend:/var/log/myapp/backend:ro
    depends_on:
      - loki
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    command:
      - "--config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - ./loki-data/chunks:/loki/chunks
      - ./loki-data/index:/loki/index
      - ./loki-data/index_cache:/loki/index_cache
      - ./loki-data/wal:/loki/wal
      - ./loki-data/compactor:/loki/compactor
    ports:
      - "3100:3100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3200:3000"
    depends_on:
      - loki
    networks:
      - monitoring

volumes:
  loki_data: {}

networks:
  monitoring: {}
  fabric_test: {}
