services:

  agent:
    image: grafana/agent:latest
    container_name: grafana-agent
    environment:
      - AGENT_MODE=flow
    command: ["run", "/etc/agent/config.river"]
    volumes:
      - ./agent-config.river:/etc/agent/config.river:ro
      - ./logs/backend:/var/log/myapp/backend:ro
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    command:
      - "--config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - ./loki-data/chunks:/loki/chunks
      - ./loki-data/index:/loki/index
      - ./loki-data/index_cache:/loki/index_cache
      - ./loki-data/wal:/loki/wal
      - ./loki-data/compactor:/loki/compactor
    ports:
      - "3100:3100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3200:3000"
    depends_on:
      - loki
    networks:
      - monitoring

volumes:
  loki_data: {}

networks:
  monitoring: {}
