image: node:20

stages:
  - lint
  - build
  - test

did_lint:
  stage: lint
  script:
    - npm ci
    - npm run lint
  artifacts:
    paths: 
        - chaincodeDID/node_modules

did_build:
  stage: build
  script:
    - npm run build
  needs: ["did_lint"]
  dependencies:
    - did_lint
  artifacts:
    paths: 
        - chaincodeDID/build

did_test:
  stage: test
  script:
    - npm run test
  needs: ["did_lint", "did_build"]
  dependencies:
    - did_lint
    - did_build
